defmodule ImaginativeRestoration.Repo.Migrations.RemovePromptTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sketches) do
      remove :label
      remove :cropped
    end
  end

  def down do
    alter table(:sketches) do
      add :cropped, :text
      add :label, :text
    end
  end
end
