defmodule ImaginativeRestoration.Repo.Migrations.AddInsertedAtIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:sketches, ["inserted_at"])
  end

  def down do
    drop_if_exists index(:sketches, ["inserted_at"], name: "sketches_inserted_at_index")
  end
end