defmodule ImaginativeRestoration.Repo.Migrations.AddImageBlobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sketches) do
      add :raw_data, :binary
      add :processed_data, :binary
      add :thumbnail, :binary
    end
  end

  def down do
    alter table(:sketches) do
      remove :thumbnail
      remove :processed_data
      remove :raw_data
    end
  end
end