defmodule ImaginativeRestoration.Repo.Migrations.DropLegacyColumns do
  @moduledoc """
  Drops the legacy text data-URL columns (`raw`, `processed`) after the
  blob backfill completed. New code reads from `raw_data` / `processed_data`
  / `thumbnail` only. `VACUUM` should be run after this migration to
  reclaim the disk space the dropped columns leave behind.

  Generated by `mix ash_sqlite.generate_migrations` and then manually
  uncommented — the generator hides destructive operations behind comments.
  """

  use Ecto.Migration

  def up do
    alter table(:sketches) do
      remove :processed
      remove :raw
    end
  end

  def down do
    alter table(:sketches) do
      add :raw, :text, null: false
      add :processed, :text
    end
  end
end
