defmodule ImaginativeRestoration.Repo.Migrations.WebhookRefactor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sketches) do
      add :intermediate_image, :text
      add :prediction_id, :text
      add :error, :text
      # default :succeeded backfills existing rows that already have a
      # `processed` image; new rows get :created via Ash, not the DB default.
      add :state, :text, null: false, default: "succeeded"
    end
  end

  def down do
    alter table(:sketches) do
      remove :state
      remove :error
      remove :prediction_id
      remove :intermediate_image
    end
  end
end
